package cn.edu.hzvtc.entity;

import javax.validation.constraints.Email;
import javax.validation.constraints.Pattern;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.id
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.ad_name
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    @Email
    private String adName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.ad_password
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    @Pattern(regexp = "(^[a-zA-Z0-9)]{6,16}$)",message = "密码必须是6-16的数字或字母!")
    private String adPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.id
     *
     * @return the value of tbl_admin.id
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.id
     *
     * @param id the value for tbl_admin.id
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.ad_name
     *
     * @return the value of tbl_admin.ad_name
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    public String getAdName() {
        return adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.ad_name
     *
     * @param adName the value for tbl_admin.ad_name
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    public void setAdName(String adName) {
        this.adName = adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.ad_password
     *
     * @return the value of tbl_admin.ad_password
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    public String getAdPassword() {
        return adPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.ad_password
     *
     * @param adPassword the value for tbl_admin.ad_password
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    public void setAdPassword(String adPassword) {
        this.adPassword = adPassword;
    }
}