package cn.edu.hzvtc.dao;

import cn.edu.hzvtc.entity.Admin;
import java.util.List;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    Admin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    List<Admin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin
     *
     * @mbg.generated Sat Jul 03 23:40:01 CST 2021
     */
    int updateByPrimaryKey(Admin record);

    List<Admin> chkAdmin(Admin admin);
}