package cn.edu.hzvtc.dao;

import cn.edu.hzvtc.entity.Employee;
import java.util.List;

public interface EmployeeMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Thu Jul 01 09:17:31 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Thu Jul 01 09:17:31 CST 2021
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Thu Jul 01 09:17:31 CST 2021
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Thu Jul 01 09:17:31 CST 2021
     */
    List<Employee> selectAll();

    List<Employee> selectAllWithDept();

    List<Employee> selectEmpsByList(List<Integer> ids);

    int deleteByList(List<Integer> ids);

    List<Employee> selectEmpsByName(String empName);

    Employee selectAllWithDeptByEmpId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Thu Jul 01 09:17:31 CST 2021
     */
    int updateByPrimaryKey(Employee record);
}